unit UDams;

{Auto-generated by Dam - 26/09/2020 23:21:19}

interface

uses DamUnit;

function DamParams(const Params: array of Variant): TDamParams;

procedure MsgInfo(const Msg: String; const Params: TDamParams = nil);
procedure MsgWarn(const Msg: String; const Params: TDamParams = nil);
procedure MsgError(const Msg: String; const Params: TDamParams = nil);
function MsgQuest(const Msg: String; const Params: TDamParams = nil): Boolean;
procedure MsgRaise(const Msg: String; const Params: TDamParams = nil);
function CaptureErrorMsg: String;
procedure ShowErrorMsg;

function QuestionCloseApp: Boolean;
function QuestionKillPlayer: Boolean;

implementation

uses UFrmMain;

function DamParams(const Params: array of Variant): TDamParams;
begin
  Result := DamUnit.DamParams(Params);
end;

procedure MsgInfo(const Msg: String; const Params: TDamParams);
begin
  DamUnit.MsgInfo(Msg, Params);
end;

procedure MsgWarn(const Msg: String; const Params: TDamParams);
begin
  DamUnit.MsgWarn(Msg, Params);
end;

procedure MsgError(const Msg: String; const Params: TDamParams);
begin
  DamUnit.MsgError(Msg, Params);
end;

function MsgQuest(const Msg: String; const Params: TDamParams): Boolean;
begin
  Result := DamUnit.MsgQuest(Msg, Params);
end;

procedure MsgRaise(const Msg: String; const Params: TDamParams);
begin
  DamUnit.MsgRaise(Msg, Params);
end;

function CaptureErrorMsg: String;
begin
  Result := DamUnit.CaptureErrorMsg;
end;

procedure ShowErrorMsg;
begin
  DamUnit.ShowErrorMsg;
end;

//-- Messages methods of TDamMsg objects

function QuestionCloseApp: Boolean;
begin
  Result := FrmMain._QuestionCloseApp.RunAsBool;
end;

function QuestionKillPlayer: Boolean;
begin
  Result := FrmMain._QuestionKillPlayer.RunAsBool;
end;

end.
